### ISSUE TITLE
BUG: Cursor jumps to end of line on input field in Chrome

### ISSUE THREAD

**Issue by florabtw** [ncpierson/soundoftext-python#3]
Reproduce:

Enter text in input field
Press back key
Notice cursor jumps back to the end

This may happen in more browsers than just Chrome

**Comment by patik** [comment]
This behavior is caused by the isHappy jQuery plugin. It looks like that plugin only serves to display an error message if the field is empty or contains only whitespace. If it's okay with you, I'd like to open a PR replace isHappy with a custom validator.

**Comment by patik** [comment]
This behavior is caused by the isHappy jQuery plugin. It looks like that plugin only serves to display an error message if the inputs contains over 100 characters. If it's okay with you, I'd like to open a PR replace isHappy with a custom validator.

**Comment by florabtw** [comment]
Hey Patik, that's totally fine! Thanks for asking first.
